Repository yapms/yapms, pull requests merged in 2023-09, with the labels that each got.

#327 Fix Blurry Map on iOS
  apps/yapms/src/lib/components/navbar/NavBar.svelte
Labels: bug

#328 Pinch to zoom caused entire page to zoom
  apps/yapms/src/lib/utils/applyPanZoom.ts
Labels: bug

#329 Revert to checkbox for modals
  apps/yapms/src/lib/components/modals/ModalBase.svelte
Labels: bug

#325 Custom Colors
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/ModalBase.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/PresetColorsModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/customcolors/AddCustomColorModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/customcolors/ColorButton.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/customcolors/CustomColor.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/customcolors/EditCustomColorModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/presetcolors/PresetColorsHeader.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/presetcolors/PresetColorsModal.svelte
  apps/yapms/src/lib/stores/CustomColors.ts
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/lib/types/CustomColor.ts
  apps/yapms/src/routes/app/+layout.svelte
  pnpm-lock.yaml
Labels: enhancement

#346 Stripes for split states
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/lib/types/Region.ts
  apps/yapms/src/lib/utils/importMap.ts
  apps/yapms/src/lib/utils/loadRegions.ts
  apps/yapms/src/lib/utils/luma.ts
  apps/yapms/src/lib/utils/patterns.ts
Labels: enhancement

#351 Added a privacy policy notification
  .env.vault
  .github/workflows/lint-project.yml
  apps/yapms/src/lib/components/modals/authmodal/AuthModal.svelte
Labels: enhancement

#352 Added apple-touch-icons
  apps/yapms/static/apple-touch-icon-precomposed.png
  apps/yapms/static/apple-touch-icon.png
Labels: bug

#354 Updated Login Formatting
  apps/yapms/src/lib/components/modals/authmodal/AccountForm.svelte
  apps/yapms/src/lib/components/modals/authmodal/AuthModal.svelte
  apps/yapms/src/lib/components/modals/authmodal/LoginForm.svelte
  apps/yapms/src/lib/components/navbar/NavBar.svelte
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/routes/+page.svelte
Labels: enhancement, refactor

#353 Region tooltip
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
  apps/yapms/src/lib/components/tooltips/RegionTooltip.svelte
  apps/yapms/src/lib/stores/RegionTooltip.ts
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/routes/app/+layout.svelte
  pnpm-lock.yaml
Labels: enhancement

#361 Ability to Reorder Candidates
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/candidatemodal/CandidateModal.svelte
  apps/yapms/src/lib/icons/Bars3.svelte
  apps/yapms/src/lib/icons/QuestionMarkCircle.svelte
  pnpm-lock.yaml
Labels: enhancement

#321 Dynamic Links
  apps/pocketbase/migrations/1693919204_created_links.go
  apps/pocketbase/migrations/1693919250_updated_links.go
  apps/pocketbase/migrations/1694807878_updated_links.go
  apps/pocketbase/migrations/1694808071_updated_links.go
  apps/yapms/src/lib/components/homepage/HomePageSidebar.svelte
  apps/yapms/src/lib/components/links/SocialLinkGrid.svelte
  apps/yapms/src/lib/components/sidebar/SideBar.svelte
Labels: enhancement

#364 Move Images out of Public Directory
  apps/yapms/src/lib/assets/images/countries/aus.webp
  apps/yapms/src/lib/assets/images/countries/can.webp
  apps/yapms/src/lib/assets/images/countries/dnk.webp
  apps/yapms/src/lib/assets/images/countries/gbr.webp
  apps/yapms/src/lib/assets/images/countries/ita.webp
  apps/yapms/src/lib/assets/images/countries/nld.webp
  apps/yapms/src/lib/assets/images/countries/nzl.webp
  apps/yapms/src/lib/assets/images/countries/usa.webp
  apps/yapms/src/lib/assets/images/countries/usahouse.webp
  apps/yapms/src/lib/assets/images/countries/usapres.webp
  apps/yapms/src/lib/assets/images/countries/usastatehouse.webp
  apps/yapms/src/lib/assets/images/countries/usastatesenate.webp
  apps/yapms/src/lib/components/homepage/MapSelectionCard.svelte
Labels: refactor

#367 Add pan-zoom to view route
  apps/yapms/src/routes/view/+page.svelte
Labels: bug

#366 Cleanup imports and map loading
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SavedMap.svelte
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SavedMaps.svelte
  apps/yapms/src/lib/stores/LoadedMap.ts
  apps/yapms/src/routes/app/+layout.svelte
  apps/yapms/src/routes/app/+page.svelte
  apps/yapms/src/routes/app/[country]/+layout.svelte
  apps/yapms/src/routes/view/+page.svelte
Labels: refactor

#381 Change pres '22 to pres '24
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2024-blank.svg
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/src/routes/app/[country]/[map]/[year]/[variant]/+page.server.ts
Labels: bug

#383 Side bar on mobile
  apps/yapms/src/lib/components/navbar/NavBar.svelte
  apps/yapms/src/lib/components/sidebar/SideBar.svelte
  apps/yapms/src/lib/stores/SideBar.ts
  apps/yapms/src/routes/app/+layout.svelte
Labels: enhancement

#384 Allow Maps & Charts to shrink
  apps/yapms/src/lib/components/charts/battlechart/BattleChart.svelte
  apps/yapms/src/lib/components/charts/piechart/PieChart.svelte
  apps/yapms/src/lib/components/mapchartcontainer/MapChartContainer.svelte
Labels: bug

#370 Refactor Import Logic
  apps/yapms/src/lib/utils/importMap.ts
Labels: refactor

#385 Border Size Slider
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
  apps/yapms/src/lib/stores/AutoStrokeMultiplierStore.ts
  apps/yapms/src/lib/utils/applyPanZoom.ts
Labels: enhancement
