Repository yapms/yapms, pull requests merged in 2023-11, with the labels that each got.

#430 South African source change
  apps/yapms/src/lib/assets/maps/saf/saf-municipalities-2019275-blank.svg
  apps/yapms/src/lib/assets/maps/saf/saf-nat_assem-2019-blank.svg
  apps/yapms/src/lib/assets/maps/saf/saf-nat_assem-2019-results.svg
  apps/yapms/src/lib/assets/maps/saf/saf-national_assembly-2019128-results.svg
  apps/yapms/src/lib/assets/maps/saf/saf-national_assembly-2019281-blank.svg
  apps/yapms/src/lib/assets/maps/saf/saf-provinces.svg
  apps/yapms/src/lib/components/mapcard/mapcards/SAFMapCard.svelte
Labels: bug, documentation

#431 Custom Logo
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
Labels: enhancement

#432 Always update sources on sidebar
  apps/yapms/src/lib/components/sidebar/sections/sources/Sources.svelte
  apps/yapms/src/lib/stores/OriginalSource.ts
  apps/yapms/src/lib/stores/SideBar.ts
  apps/yapms/src/lib/utils/loadRegions.ts
  apps/yapms/src/routes/app/[country]/+layout.svelte
Labels: bug

#433 Fix no grey modal background
  apps/yapms/src/lib/components/modals/ModalBase.svelte
Labels: bug

#434 Navigate Home Modal
  apps/yapms/src/lib/components/modals/clearmapmodal/ClearMapModal.svelte
  apps/yapms/src/lib/components/modals/navigatehomemodal/NavigateHomeModal.svelte
  apps/yapms/src/lib/components/navbar/NavBar.svelte
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/routes/app/+layout.svelte
Labels: enhancement

#435 Fix South African Card & Country Code
  apps/yapms/src/lib/assets/images/countries/zaf.webp
  apps/yapms/src/lib/assets/maps/zaf/zaf-municipalities-2019275-blank.svg
  apps/yapms/src/lib/assets/maps/zaf/zaf-national_assembly-2019128-blank.svg
  apps/yapms/src/lib/assets/maps/zaf/zaf-national_assembly-2019128-results.svg
  apps/yapms/src/lib/assets/maps/zaf/zaf-provinces.svg
  apps/yapms/src/lib/components/mapcard/mapcards/SAFMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/ZAFMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: bug

#436 Compress Screenshot
  .devcontainer/devcontainer.json
  Dockerfile.pocketbase
  README.md
  apps/pocketbase/support/takeScreenshot.go
  package-lock.json
Labels: enhancement

#439 Remove Beta Modal
  apps/yapms/src/lib/components/modals/betamodal/BetaModal.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#440 World countries map
  apps/yapms/src/lib/assets/images/countries/glb.webp
  apps/yapms/src/lib/assets/maps/glb/glb-countries-2020078-blank.svg
  apps/yapms/src/lib/components/mapcard/MapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/GLBMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#442 Update ENV urls
  .env.vault
Labels: bug

#441 Fix SEO issues pointed out by lighthouse on homepage.
  apps/yapms/src/lib/components/modals/ModalBase.svelte
  apps/yapms/src/lib/components/modals/importmodal/ImportModal.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#444 Bring back original import text
  apps/yapms/src/lib/components/modals/importmodal/ImportModal.svelte
Labels: enhancement

#443 Fix zooming on click for piechart
  apps/yapms/src/lib/components/charts/piechart/PieChart.svelte
Labels: bug

#445 Replace Aqua with Dracula
  apps/yapms/src/lib/components/modals/thememodal/ThemeGrid.svelte
  apps/yapms/tailwind.config.cjs
Labels: enhancement

#446 Compress Homepage Images
  apps/yapms/src/lib/assets/images/countries/aus.webp
  apps/yapms/src/lib/assets/images/countries/bra.webp
  apps/yapms/src/lib/assets/images/countries/can.webp
  apps/yapms/src/lib/assets/images/countries/canlegassem.webp
  apps/yapms/src/lib/assets/images/countries/dnk.webp
  apps/yapms/src/lib/assets/images/countries/fra.webp
  apps/yapms/src/lib/assets/images/countries/gbr.webp
  apps/yapms/src/lib/assets/images/countries/glb.webp
  apps/yapms/src/lib/assets/images/countries/ita.webp
  apps/yapms/src/lib/assets/images/countries/nld.webp
  apps/yapms/src/lib/assets/images/countries/nzl.webp
  apps/yapms/src/lib/assets/images/countries/usa.webp
  apps/yapms/src/lib/assets/images/countries/usahouse.webp
  apps/yapms/src/lib/assets/images/countries/usapres.webp
  apps/yapms/src/lib/assets/images/countries/usastatehouse.webp
  apps/yapms/src/lib/assets/images/countries/usastatesenate.webp
  apps/yapms/src/lib/assets/images/countries/zaf.webp
Labels: enhancement

#464 Test moving from devDependencies to dependencies
  apps/yapms/package.json
  package-lock.json
Labels: bug

#463 Give updatebar a width on MD size
  apps/yapms/src/lib/components/updatessidebar/UpdatesSidebar.svelte
Labels: bug

#466 German maps
  apps/yapms/src/lib/assets/images/countries/deu.webp
  apps/yapms/src/lib/assets/maps/deu/deu-bundesrat-2023001-blank.svg
  apps/yapms/src/lib/assets/maps/deu/deu-bundestag-2021269-blank.svg
  apps/yapms/src/lib/assets/maps/deu/deu-bundestag-2021269-results.svg
  apps/yapms/src/lib/assets/maps/deu/deu-states-2023001-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/DEUMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#460 Disable the save button on imported maps.
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SaveMap.svelte
Labels: bug

#467 Add a percentage to the split modal
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/splitregionmodal/SplitRegionModal.svelte
  apps/yapms/src/lib/styles/global.css
  apps/yapms/tailwind.config.cjs
  package-lock.json
Labels: enhancement

#468 Remove minimum zoom level
  apps/yapms/src/lib/utils/applyPanZoom.ts
Labels: bug

#470 USA States map & primary updates
  apps/yapms/src/lib/assets/maps/usa/usa-dem_primary-2024-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-rep_primary-2024-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-states_and_territories-2023001-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/USAMapCard.svelte
Labels: enhancement

#469 Action Groups
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2020-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2023-blank.svg
  apps/yapms/src/lib/components/sidebar/sections/shortcuts/Shortcuts.svelte
  apps/yapms/src/lib/stores/ActionGroups.ts
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/lib/stores/regions/regionActions.ts
  apps/yapms/src/lib/types/Region.ts
  apps/yapms/src/lib/utils/loadRegions.ts
  apps/yapms/src/routes/app/[country]/+layout.svelte
  tools/add-groups-to-counties.awk
Labels: enhancement

#471 Action groups for USA house
  apps/yapms/src/lib/assets/maps/usa/usa-house-1992-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-1994-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-1996-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-1998-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2000-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2002-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2004-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2006-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2008-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2010-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2012-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2014-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2016-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2018-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2020-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2022-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2022-results.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2023298-blank.svg
  tools/add-groups-to-house.awk
Labels: enhancement

#472 Ignore Action Groups In Map Saves
  apps/yapms/src/lib/types/Region.ts
Labels: bug

#474 Open links in new tab
  apps/yapms/src/lib/components/links/SocialLinkGrid.svelte
Labels: enhancement

#475 Sidebar toggle button visual fix
  apps/yapms/src/lib/components/navbar/NavBar.svelte
Labels: bug

#473 Region Search
  apps/yapms/src/lib/components/sidebar/SideBar.svelte
  apps/yapms/src/lib/components/sidebar/sections/regionsearch/RegionSearch.svelte
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/lib/types/Region.ts
  apps/yapms/src/lib/utils/loadRegions.ts
Labels: enhancement

#476 Cleanup Images
  apps/yapms/src/lib/assets/flags/aus.svg
  apps/yapms/src/lib/assets/flags/can.svg
  apps/yapms/src/lib/assets/flags/gbr.svg
  apps/yapms/src/lib/assets/flags/usa.svg
  apps/yapms/src/lib/assets/images/logos/lte.png
  apps/yapms/src/lib/assets/images/logos/rep.png
  apps/yapms/src/lib/components/chartarea/ChartArea.svelte
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
Labels: enhancement

#478 Fix New Zealand titles & 1964 pres
  apps/yapms/src/lib/assets/maps/nzl/nzl-house-2023-blank.svg
  apps/yapms/src/lib/assets/maps/nzl/nzl-regions-2023-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-1964-results.svg
Labels: bug

#479 Deploy Docs Manually
  .github/workflows/deploy-docs.yml
Labels: enhancement

#500 Alaskan county fix
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2020-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2023-blank.svg
Labels: bug

#477 Revamp Edit Candidate Modal
  apps/yapms/src/lib/components/modals/ModalBase.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/AddCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/CandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditTossupModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/presetcolors/PresetColorsModal.svelte
  apps/yapms/src/lib/icons/Trash.svelte
  apps/yapms/src/lib/stores/Candidates.ts
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/lib/stores/regions/Regions.ts
Labels: enhancement

#501 Korea - National Assembly & Municipalities
  apps/yapms/src/lib/assets/images/countries/kor.webp
  apps/yapms/src/lib/assets/maps/kor/kor-municipalities-2018001-blank.svg
  apps/yapms/src/lib/assets/maps/kor/kor-national_assembly-2020001-blank.svg
  apps/yapms/src/lib/components/mapcard/MapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/KORMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#510 Improved USA counties
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2020-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2023-blank.svg
Labels: bug, enhancement
