Repository yapms/yapms, pull requests merged in 2023-10, with the labels that each got.

#387 Update ENV vault
  .env.vault
Labels: dependency upgrade

#388 Remove Map Name Text on Save
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SaveMap.svelte
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SavedMap.svelte
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SavedMaps.svelte
Labels: bug

#386 Remove Shortcuts on Small Screens
  apps/yapms/src/lib/components/sidebar/sections/shortcuts/Shortcuts.svelte
Labels: enhancement

#389 Cache Updates & Social Links
  apps/pocketbase/main.go
Labels: enhancement

#390 Prevent cache on AdminUI
  apps/pocketbase/main.go
Labels: bug

#393 2024 House AL update
  apps/yapms/src/lib/assets/maps/usa/usa-house-2024-blank.svg
Labels: bug

#399 Environment Setup With Docker
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .gitignore
  pnpm-lock.yaml
Labels: enhancement

#400 Canadian provincial maps
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/images/countries/canlegassem.webp
  apps/yapms/src/lib/assets/maps/can/can-ab-2023-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-bc-2020-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-mb-2023-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-nb-2020-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-nl-2021-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-ns-2021-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-nt-2023-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-on-2022-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-pe-2023-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-qc-2022-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-sk-2024-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-yt-2021-blank.svg
  apps/yapms/src/lib/assets/other/Titles.json
Labels: enhancement

#391 Better Mobile Navigation
  apps/yapms/src/lib/components/navbar/NavBar.svelte
Labels: enhancement

#401 Easier Devcontainer
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/workflows/lint-project.yml
  README.md
  apps/docs/package.json
  apps/yapms/.npmrc
  docker-compose.development.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: bug

#406 Fix quebec party name
  apps/yapms/src/lib/assets/maps/can/can-qc-2022-blank.svg
Labels: bug

#414 Fix search for a Windows server
  apps/yapms/src/routes/+page.server.ts
Labels: bug

#412 Remove map selection json ** REVIEW AFTER PR 411 **
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/components/homepage/MapSelectionGrid.svelte
  apps/yapms/src/lib/components/homepage/MapSelectionTitle.svelte
  apps/yapms/src/lib/components/mapcard/MapCard.svelte
  apps/yapms/src/lib/components/mapcard/MapCardGrid.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/AUSMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/CANMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/CANProvincesMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/DNKMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/FRAMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/GBRMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/ITAMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/NLDMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/NZLMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/USACongressionalMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/USAMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/USAPresidentialMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/USAStateHouseMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/USAStateSenateMapCard.svelte
  apps/yapms/src/lib/components/mapsearch/MapSearch.svelte
  apps/yapms/src/lib/components/updatessidebar/Update.svelte
  apps/yapms/src/lib/components/updatessidebar/UpdatesSidebar.svelte
  apps/yapms/src/routes/+page.svelte
Labels: refactor

#410 Canadian updates
  apps/yapms/src/lib/assets/maps/can/can-bc-2023107-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-2023201-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-next-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/CANMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/CANProvincesMapCard.svelte
Labels: enhancement

#415 New North Carolina maps
  apps/yapms/src/lib/assets/maps/usa/usa-house-2023298-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-house-2024-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-nc_lower-2023298-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-nc_upper-2023298-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/USAStateHouseMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/USAStateSenateMapCard.svelte
Labels: bug, enhancement

#419 Brazilian maps
  apps/yapms/src/lib/assets/images/countries/bra.webp
  apps/yapms/src/lib/assets/maps/bra/bra-deputies-2022-blank.svg
  apps/yapms/src/lib/assets/maps/bra/bra-regions-2023-blank.svg
  apps/yapms/src/lib/assets/maps/bra/bra-senate-2022-blank.svg
  apps/yapms/src/lib/assets/maps/bra/bra-senate.svg
  apps/yapms/src/lib/components/mapcard/mapcards/BRAMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#426 Increase size of save file to 0.5 MB
  apps/pocketbase/migrations/1698615145_updated_maps.go
  apps/pocketbase/migrations/1698615826_updated_user_maps.go
Labels: bug

#428 SAF maps & import fixes
  apps/yapms/src/lib/assets/images/countries/saf.webp
  apps/yapms/src/lib/assets/maps/saf/saf-municipalities-2023-blank.svg
  apps/yapms/src/lib/assets/maps/saf/saf-nat_assem-2019-blank.svg
  apps/yapms/src/lib/assets/maps/saf/saf-nat_assem-2019-results.svg
  apps/yapms/src/lib/assets/maps/saf/saf-provinces.svg
  apps/yapms/src/lib/components/mapcard/mapcards/SAFMapCard.svelte
  apps/yapms/src/lib/utils/importMap.ts
  apps/yapms/src/routes/+page.svelte
Labels: bug, enhancement
