Repository yapms/yapms, pull requests merged in 2023-07, with the labels that each got.

#202 MoreMapsModal Rework
  apps/yapms/src/lib/assets/homedata/MapList.json
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/src/lib/components/homepage/MapSelectionCard.svelte
  apps/yapms/src/lib/components/modals/moremapsmodal/MoreMapsModal.svelte
  apps/yapms/src/lib/stores/HomeModals.ts
  apps/yapms/src/lib/types/HomeData.ts
  apps/yapms/src/lib/types/HomeLinkData.ts
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#203 Proper selection of SVG when exporting
  apps/yapms/src/lib/utils/importMap.ts
Labels: bug

#211 Canadian Maps
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/maps/can/can-commons-2015-results.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-2019-results.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-2021-results.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-provinces-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-senate-blank.svg
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/static/countrybackgrounds/can.webp
Labels: enhancement

#209 Insets
  apps/yapms/src/lib/assets/maps/debug/debug-inset-regions.svg
  apps/yapms/src/lib/components/modals/stylemodal/StyleModal.svelte
  apps/yapms/src/lib/stores/MapInsetsStore.ts
  apps/yapms/src/lib/styles/global.css
  apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
  apps/yapms/src/routes/app/imported/+page.svelte
Labels: enhancement

#212 Fix browserless screenshot
  apps/pocketbase/support/takeScreenshot.go
Labels: bug

#214 Set body width using percent
  apps/yapms/src/lib/styles/global.css
  apps/yapms/src/routes/+page.svelte
Labels: bug

#217 Replace candidate-id, candidate-margin with candidates prop
  apps/yapms/src/lib/assets/maps/can/can-commons-2015-results.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-2019-results.svg
  apps/yapms/src/lib/assets/maps/can/can-commons-2021-results.svg
  apps/yapms/src/lib/assets/maps/debug/debug-predetermined-regions.svg
  apps/yapms/src/lib/assets/maps/usa-house/usa-house-current.svg
  apps/yapms/src/lib/assets/maps/usa/usa-governors-current.svg
  apps/yapms/src/lib/assets/maps/usa/usa-senate-current.svg
  apps/yapms/src/lib/types/Region.ts
  apps/yapms/src/lib/utils/importMap.ts
  apps/yapms/src/routes/app/[country]/[map]/[year]/initialize/LoadRegions.ts
Labels: enhancement

#223 Dutch Maps
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/maps/nld/nld-gemeente-2023-blank.svg
  apps/yapms/src/lib/assets/maps/nld/nld-house-2023-blank.svg
  apps/yapms/src/lib/assets/maps/nld/nld-provinces-blank.svg
  apps/yapms/src/lib/assets/maps/nld/nld-provincial-2023-blank.svg
  apps/yapms/src/lib/assets/maps/nld/nld-provincial-2023-results.svg
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/static/countrybackgrounds/nld.webp
Labels: enhancement

#230 Tell Svelte which routes to render
  apps/yapms/src/routes/app/[country]/[map]/[year]/+page.server.ts
Labels: bug

#231 Candidate ID fix
  apps/yapms/src/lib/assets/maps/nld/nld-house-2023-blank.svg
Labels: bug

#232 British Maps
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2019-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2019-results.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2024-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-counties-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-historic-counties-blank.svg
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/static/countrybackgrounds/gbr.webp
Labels: enhancement

#237 Fix modern counties, 2024 commons candidates
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2024-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-counties-blank.svg
Labels: bug

#235 Fix map oversensitivity on mobile
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/routes/app/[country]/[map]/[year]/initialize/ApplyPanZoom.ts
Labels: bug

#241 Prevent closing of MoreMapsModal when opening in new tab
  apps/yapms/src/lib/components/modals/moremapsmodal/MoreMapsModal.svelte
Labels: enhancement

#244 Danish Maps
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/maps/de/de-folketing-blank.svg
  apps/yapms/src/lib/assets/maps/dnk/dnk-folketing-2022-blank.svg
  apps/yapms/src/lib/assets/maps/dnk/dnk-folketing-2022-results.svg
  apps/yapms/src/lib/assets/maps/dnk/dnk-municipalities-blank.svg
  apps/yapms/src/lib/assets/maps/dnk/dnk-regions-blank.svg
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/static/countrybackgrounds/dnk.webp
Labels: enhancement

#249 reapplyPanZoom on chart changes
  apps/yapms/src/lib/components/mapchartcontainer/MapChartContainer.svelte
  apps/yapms/src/lib/components/modals/chartoptionsmodal/ChartOptionsModal.svelte
  apps/yapms/src/lib/components/sidebar/SideBar.svelte
  apps/yapms/src/lib/utils/applyPanZoom.ts
  apps/yapms/src/routes/app/+layout.svelte
  apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
  apps/yapms/src/routes/app/imported/+page.svelte
Labels: bug

#260 Error page
  apps/yapms/src/routes/+error.svelte
Labels: enhancement

#266 Italian Maps
  apps/yapms/src/lib/assets/homedata/MapSelection.json
  apps/yapms/src/lib/assets/maps/ita/ita-deputies-2022-blank.svg
  apps/yapms/src/lib/assets/maps/ita/ita-deputies-2022-results.svg
  apps/yapms/src/lib/assets/maps/ita/ita-provinces-2023-blank.svg
  apps/yapms/src/lib/assets/maps/ita/ita-regions-2023-blank.svg
  apps/yapms/src/lib/assets/maps/ita/ita-senate-2022-blank.svg
  apps/yapms/src/lib/assets/maps/ita/ita-senate-2022-results.svg
  apps/yapms/src/lib/assets/other/Titles.json
  apps/yapms/static/countrybackgrounds/ita.webp
Labels: enhancement

#270 Fix duplicate county IDs
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2023-blank.svg
Labels: bug

#271 Update to Pocketbase 1.70
  apps/pocketbase/go.mod
  apps/pocketbase/go.sum
  apps/pocketbase/main.go
  apps/yapms/package.json
  pnpm-lock.yaml
Labels: dependency upgrade

#272 Remove cache on build command
  turbo.json
Labels: bug

#273 Errors on generate link
  apps/pocketbase/main.go
  apps/pocketbase/support/verifyCaptcha.go
  apps/yapms/src/lib/components/modals/sharemodal/ShareModal.svelte
Labels: bug

#274 Fix deployment issues and some UI errors on share
  apps/yapms/src/lib/components/modals/sharemodal/ShareModal.svelte
  deployment/playbooks/deploy.yml
Labels: bug
