Repository yapms/yapms, pull requests merged in 2024-02, with the labels that each got.

#564 Move logos to CMS
  apps/pocketbase/migrations/1706590699_created_creator_logos.go
  apps/pocketbase/migrations/1706591045_updated_creator_logos.go
  apps/pocketbase/migrations/1706591258_updated_creator_logos.go
  apps/yapms/src/lib/assets/images/logos/lte.png
  apps/yapms/src/lib/assets/images/logos/pa.png
  apps/yapms/src/lib/assets/images/logos/rep.png
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
Labels: enhancement

#565 Remember the users font size
  apps/yapms/src/lib/stores/CandidateBoxOptions.ts
Labels: enhancement

#566 Irish maps
  apps/yapms/src/lib/assets/images/countries/irl.webp
  apps/yapms/src/lib/assets/maps/irl/irl-counties-2019001-blank.svg
  apps/yapms/src/lib/assets/maps/irl/irl-dail-2020039-blank.svg
  apps/yapms/src/lib/assets/maps/irl/irl-dail-2020039-results.svg
  apps/yapms/src/lib/assets/maps/irl/irl-dail-2024031-blank.svg
  apps/yapms/src/lib/assets/maps/irl/irl-dail-next-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/IRLMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#567 Add font color option.
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
  apps/yapms/src/lib/stores/FontColorStore.ts
  apps/yapms/src/lib/stores/regions/Regions.ts
Labels: enhancement

#568 Update Minor Packages
  apps/yapms/package.json
  apps/yapms/src/lib/components/links/SocialLinkGrid.svelte
  package-lock.json
Labels: dependency upgrade

#571 Update Pocketbase
  apps/pocketbase/go.mod
  apps/pocketbase/go.sum
  apps/yapms/package.json
  package-lock.json
Labels: dependency upgrade

#572 Update Turborepo
  package-lock.json
  package.json
Labels: dependency upgrade

#573 Delete Docs
  apps/docs/.gitignore
  apps/docs/.vscode/extensions.json
  apps/docs/.vscode/launch.json
  apps/docs/README.md
  apps/docs/astro.config.mjs
  apps/docs/package.json
  apps/docs/public/favicon.svg
  apps/docs/src/assets/houston.webp
  apps/docs/src/content/config.ts
  apps/docs/src/content/docs/guides/example.md
  apps/docs/src/content/docs/index.mdx
  apps/docs/src/content/docs/reference/example.md
  apps/docs/src/env.d.ts
  apps/docs/tsconfig.json
  package-lock.json
  package.json
Labels: refactor

#578 Update to Sveltekit 2
  apps/yapms/package.json
  apps/yapms/src/lib/components/candidatebox/CandidateBox.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/CandidateModal.svelte
  apps/yapms/src/lib/components/modals/sharemodal/ShareModal.svelte
  apps/yapms/src/lib/components/modals/splitregionmodal/SplitRegionModal.svelte
  apps/yapms/src/lib/stores/Candidates.ts
  apps/yapms/src/lib/stores/Chart.ts
  apps/yapms/src/lib/stores/CustomColors.ts
  apps/yapms/src/lib/stores/ImportedSVG.ts
  apps/yapms/src/lib/stores/LoadedMap.ts
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/lib/types/Candidate.ts
  apps/yapms/src/lib/types/ChartPosition.ts
  apps/yapms/src/lib/types/CustomColor.ts
  apps/yapms/src/lib/types/HomeData.ts
  apps/yapms/src/lib/types/ImportedSVG.ts
  apps/yapms/src/lib/types/Region.ts
  apps/yapms/src/lib/types/SavedMap.ts
  apps/yapms/src/lib/utils/importMap.ts
  apps/yapms/src/lib/utils/loadRegions.ts
  apps/yapms/src/lib/utils/saveMap.ts
  apps/yapms/vite.config.ts
  package-lock.json
  turbo.json
Labels: dependency upgrade

#581 Handle NaN on map load
  apps/yapms/src/lib/utils/loadRegions.ts
Labels: bug

#580 Ability to map imported region properties to GeoJSON properties
  apps/yapms/src/lib/components/modals/importmodal/ImportOptions.svelte
  apps/yapms/src/lib/stores/ImportedSVG.ts
  apps/yapms/src/lib/types/ImportedSVG.ts
  apps/yapms/src/lib/utils/importMap.ts
Labels: enhancement

#585 Sort User Maps Alphabetically
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SavedMaps.svelte
Labels: enhancement

#588 Automerge prettier & eslint
  renovate.json
Labels: enhancement

#590 shift+g to perform action on everything not selected
  apps/yapms/src/lib/components/sidebar/sections/shortcuts/Shortcuts.svelte
  apps/yapms/src/lib/stores/regions/Regions.ts
  apps/yapms/src/lib/stores/regions/regionActions.ts
Labels: enhancement

#596 Expose "default value" candidate property to users
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  apps/yapms/src/lib/stores/regions/Regions.ts
Labels: enhancement

#599 Fixes to can-qc-2022-blank.svg
  apps/yapms/src/lib/assets/maps/can/can-qc-2022-blank.svg
Labels: bug
