Repository yapms/yapms, pull requests merged in 2024-01, with the labels that each got.

#550 Presidential map fixes
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-1984-results.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-1988-results.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2012-results.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2016-results.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2020-results.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2024-blank.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2024-takeall.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2024-takeall_territories.svg
  apps/yapms/src/lib/assets/maps/usa/usa-presidential-2024-territories.svg
Labels: bug

#551 Portuguese maps
  apps/yapms/src/lib/assets/images/countries/prt.webp
  apps/yapms/src/lib/assets/maps/prt/prt-assembly-2024070-blank.svg
  apps/yapms/src/lib/assets/maps/prt/prt-districts-2021093-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/PRTMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#552 Fix states and territories saves
  apps/yapms/src/lib/assets/maps/usa/usa-states_and_territories-2023001-blank.svg
Labels: bug

#553 Update Pocketbase
  apps/pocketbase/go.mod
  apps/pocketbase/go.sum
  apps/yapms/package.json
  package-lock.json
Labels: dependency upgrade

#554 Fix maps where country type wasn't set properly
  apps/yapms/src/lib/assets/maps/bra/bra-deputies-2022-blank.svg
  apps/yapms/src/lib/assets/maps/bra/bra-regions-2023-blank.svg
  apps/yapms/src/lib/assets/maps/bra/bra-senate-2022-blank.svg
  apps/yapms/src/lib/assets/maps/bra/bra-senate.svg
  apps/yapms/src/lib/assets/maps/usa/usa-counties-2023-blank.svg
Labels: bug

#558 Portugal Municipalities Map
  apps/yapms/src/lib/assets/maps/prt/prt-municipalities-2018316-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/PRTMapCard.svelte
Labels: enhancement

#562 Added PA Logo
  apps/yapms/src/lib/assets/images/logos/pa.png
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
Labels: enhancement
