Repository yapms/yapms, pull requests merged in 2024-07, with the labels that each got.

#719 Downgrade DaisyUI - breaks screenshots
  apps/yapms/package.json
  package-lock.json
Labels: bug

#729 Match edit tossup modal style to other candidate modals
  apps/yapms/src/lib/components/modals/candidatemodal/EditTossupModal.svelte
Labels: enhancement

#726 Upgrade to Browserless 2.0
  .devcontainer/docker-compose.yml
  .env.vault
  apps/pocketbase/support/takeScreenshot.go
  deployment/playbooks/deploy-all.yml
Labels: dependency upgrade

#731 Sync Package Lock
  package-lock.json
Labels: bug

#732 Switch Candidate Shortcut
  apps/yapms/src/lib/components/sidebar/sections/shortcuts/Shortcuts.svelte
  apps/yapms/src/lib/stores/Candidates.ts
  apps/yapms/src/lib/utils/keyCodeToNumber.ts
  apps/yapms/src/routes/app/+layout.svelte
Labels: enhancement

#746 Ansible quote ENV variables
  deployment/playbooks/deploy-all.yml
Labels: bug

#758 New Brunswick 2024
  apps/yapms/src/lib/assets/maps/can/can-nb-2024264-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/CANProvincesMapCard.svelte
Labels: enhancement

#771 Fix Linting
  apps/yapms/src/app.html
Labels: refactor

#781 FlexGrow Updates
  apps/yapms/src/lib/components/updatessidebar/UpdatesSidebar.svelte
Labels: bug
