Repository yapms/yapms, pull requests merged in 2024-06, with the labels that each got.

#678 Update broken Lok Sabha Region ID
  apps/yapms/src/lib/assets/maps/ind/ind-lok_sabha-2024109-blank.svg
Labels: bug

#675 EditRegionModal input improvements
  apps/yapms/src/lib/components/modals/editregionmodal/EditRegionModal.svelte
Labels: enhancement

#679 Border Color Option
  apps/yapms/src/lib/components/modals/optionsmodal/OptionsModal.svelte
  apps/yapms/src/lib/stores/RegionStrokeColorStore.ts
  apps/yapms/src/lib/styles/global.css
  apps/yapms/src/routes/app/[country]/+layout.svelte
  apps/yapms/src/routes/app/imported/+page.svelte
Labels: enhancement

#682 Usa & Canada Map
  apps/yapms/src/lib/assets/images/countries/usacan.webp
  apps/yapms/src/lib/assets/maps/usa_can/usa_can-states-2024001-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/USACANMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#683 Apply auto border to rects
  apps/yapms/src/lib/styles/global.css
Labels: bug

#686 Margins for split states
  apps/yapms/src/lib/components/modals/splitregionmodal/SplitRegionModal.svelte
  apps/yapms/src/lib/utils/patterns.ts
Labels: enhancement

#687 Dots for island countries
  apps/yapms/src/lib/assets/maps/glb/glb-countries-2020078-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/GLBMapCard.svelte
Labels: enhancement

#684 Key combo to recenter map
  apps/yapms/src/lib/components/sidebar/sections/shortcuts/Shortcuts.svelte
  apps/yapms/src/routes/app/+layout.svelte
Labels: enhancement

#689 Add borders to /view route
  apps/yapms/src/routes/view/+page.svelte
Labels: bug

#691 French National Assembly map
  apps/yapms/src/lib/assets/maps/fra/fra-assembly-2024181-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/FRAMapCard.svelte
Labels: enhancement

#688 Natural Earth Countries
  apps/yapms/src/lib/assets/maps/glb/glb-countries-2020078-natural_earth.svg
  apps/yapms/src/lib/components/mapcard/mapcards/GLBMapCard.svelte
Labels: enhancement

#698 Run Audit Fix
  package-lock.json
Labels: dependency upgrade

#705 Upgrade Turborepo
  .github/workflows/lint-project.yml
  package-lock.json
  package.json
  turbo.json
Labels: dependency upgrade

#718 Update build to use turbo v2
  Dockerfile.yapms
Labels: bug
