Repository yapms/yapms, pull requests merged in 2025-06, with the labels that each got.

#1420 GBR color fix
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2019-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2019-results.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-commons-2024-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-counties-1844-blank.svg
  apps/yapms/src/lib/assets/maps/gbr/gbr-counties-2023-blank.svg
Labels: bug

#1425 Australian States & Updates
  apps/yapms/src/lib/assets/images/countries/auslegassem.webp
  apps/yapms/src/lib/assets/maps/aus/aus-act-2024292-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-house-2025123-results.svg
  apps/yapms/src/lib/assets/maps/aus/aus-nsw-2023084-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-nt-2024326-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-qld-2024299-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-sa-2026080-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-senate-2022-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-senate-2022-results.svg
  apps/yapms/src/lib/assets/maps/aus/aus-senate-2025123-results.svg
  apps/yapms/src/lib/assets/maps/aus/aus-senate.svg
  apps/yapms/src/lib/assets/maps/aus/aus-tas_lower-2024082-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-tas_upper-2025145-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-vic_lower-2022330-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-vic_upper-2022330-blank.svg
  apps/yapms/src/lib/assets/maps/aus/aus-wa-2025067-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/AUSMapCard.svelte
  apps/yapms/src/lib/components/mapcard/mapcards/AUSStatesMapCard.svelte
  apps/yapms/src/routes/+page.svelte
Labels: enhancement

#1426 German Updates
  apps/yapms/src/lib/assets/maps/deu/deu-bundesrat-2023001-blank.svg
  apps/yapms/src/lib/assets/maps/deu/deu-bundestag-2025055-blank.svg
  apps/yapms/src/lib/assets/maps/deu/deu-bundestag-2025055-results.svg
  apps/yapms/src/lib/components/mapcard/mapcards/DEUMapCard.svelte
Labels: enhancement

#1430 Generate Shades and Candidate Modal Fixes
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/candidatemodal/AddCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditTossupModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/shadegeneration/GenerateShades.svelte
  apps/yapms/src/lib/utils/inputValidation.ts
  apps/yapms/src/lib/utils/shades.ts
  package-lock.json
Labels: enhancement

#1437 Import Input Validation Functions
  apps/yapms/src/lib/components/modals/editregionmodal/EditRegionModal.svelte
  apps/yapms/src/lib/components/modals/splitregionmodal/SplitRegionModal.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/tools/MassEditModal.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/tools/TableModal.svelte
Labels: refactor

#1439 prevent alphabetic input starting value
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
Labels: bug

#1448 Flip Colors Feature
  apps/yapms/src/lib/components/modals/candidatemodal/AddCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  apps/yapms/src/lib/icons/Rotate.svelte
Labels: enhancement

#1440 TCT Game Import
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/sharemodal/ShareModal.svelte
  apps/yapms/src/lib/stores/LoadedMap.ts
  apps/yapms/src/lib/utils/loadMap.ts
  apps/yapms/src/lib/utils/safeJsonParse.ts
  apps/yapms/src/lib/utils/stateCodes.ts
  package-lock.json
Labels: enhancement

#1490 Fix MS Duplicate Region
  apps/yapms/src/lib/assets/maps/usa/usa-ms_lower-2025035-blank.svg
Labels: bug

#1492 Modal Toggle Keybinds
  apps/yapms/src/lib/components/modals/modemodal/ModeModal.svelte
  apps/yapms/src/lib/components/sidebar/sections/shortcuts/Shortcuts.svelte
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/routes/app/+layout.svelte
Labels: enhancement
