Repository yapms/yapms, pull requests merged in 2025-03, with the labels that each got.

#1158 Accept .json for GeoJSON imports
  apps/yapms/src/lib/components/modals/importmodal/ImportModal.svelte
Labels: enhancement

#1160 Polish Senate
  apps/yapms/src/lib/assets/maps/pol/pol-senate-2023288-blank.svg
  apps/yapms/src/lib/assets/maps/pol/pol-senate-2023288-results.svg
  apps/yapms/src/lib/components/mapcard/mapcards/POLMapCard.svelte
Labels: enhancement

#1159 Regions Table Tool
  apps/yapms/src/lib/components/modals/ModalBase.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/ToolsModal.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/tools/TableModal.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/tools/tablecomponents/CandidateActions.svelte
  apps/yapms/src/lib/icons/Sliders.svelte
  apps/yapms/src/lib/stores/Modals.ts
  apps/yapms/src/lib/stores/regions/regionActions.ts
  apps/yapms/src/lib/utils/patterns.ts
Labels: enhancement

#1185 Fix Linting Issues
  apps/yapms/eslint.config.js
  apps/yapms/src/lib/components/mapsearch/MapSearch.svelte
  apps/yapms/src/lib/components/modals/editregionmodal/EditRegionModal.svelte
  apps/yapms/src/lib/components/modals/splitregionmodal/SplitRegionModal.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/ToolsModal.svelte
  apps/yapms/src/lib/components/modals/toolsmodal/tools/MassEditModal.svelte
  apps/yapms/src/lib/components/sidebar/sections/regionsearch/RegionSearch.svelte
  apps/yapms/src/lib/components/sidebar/sections/savedmaps/SavedMaps.svelte
  apps/yapms/src/routes/view/+page.svelte
Labels: refactor

#1209 Fix sortable items
  apps/yapms/package.json
  apps/yapms/src/lib/components/modals/candidatemodal/AddCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/CandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  package-lock.json
Labels: bug
