Repository yapms/yapms, pull requests merged in 2025-05, with the labels that each got.

#1311 Remove Readme
  apps/yapms/README.md
Labels: refactor

#1348 Title, Sources, and Action Groups support for Imported Maps
  apps/yapms/src/lib/utils/importMap.ts
  apps/yapms/src/routes/app/imported/+page.svelte
Labels: bug

#1344 Portugal Update
  apps/yapms/src/lib/assets/maps/prt/prt-assembly-2024070-results.svg
  apps/yapms/src/lib/assets/maps/prt/prt-assembly-2025138-blank.svg
  apps/yapms/src/lib/assets/maps/prt/prt-municipalities-2018316-blank.svg
  apps/yapms/src/lib/components/mapcard/mapcards/PRTMapCard.svelte
Labels: enhancement

#1398 Fix Color Input Style on Chrome
  apps/yapms/src/lib/components/modals/candidatemodal/AddCandidateModal.svelte
  apps/yapms/src/lib/components/modals/candidatemodal/EditCandidateModal.svelte
  apps/yapms/src/lib/styles/global.css
Labels: bug
